name: workflow-actions

on: 
  push:
    branches: 
      - Website-Front-End
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: security
        env: 
          testKey: ${{ secrets.test_key }}
